export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_DATASTORE = "UPDATE_DATASTORE";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const UPDATE_STATUS_FILTER = "UPDATE_STATUS_FILTER";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const UPDATE_EDITED_ENTRY = "UPDATE_EDITED_ENTRY";
export const ADD_NEW_ENTRY = "ADD_NEW_ENTRY";
