export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_DATASTORE = "UPDATE_DATASTORE";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const UPDATE_STATUS_FILTER = "UPDATE_STATUS_FILTER";
